// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "dff0c542-27b0-4e64-a69e-52d592b4a59d");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1621699049);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1621699022);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1621699289);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1621699169);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1621699079);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1621699018);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d7f8a1bf-95f4-4ce0-8711-8b5164e03139}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1621699021);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1621699047865");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1621700871865");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1621699022441");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1621720622441");
user_pref("browser.search.region", "RU");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.homepage_override.buildID", "20210504152106");
user_pref("browser.startup.homepage_override.mstone", "88.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1621699020);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Яндекс");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1621699021193");
user_pref("distribution.iniFile.exists.appversion", "88.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "86ea6ff4fa744cccac3913783ad8841e");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210504152106");
user_pref("extensions.lastAppVersion", "88.0.1");
user_pref("extensions.lastPlatformVersion", "88.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"f3a9a5e1-78dd-4944-b236-6ed68b5e5640\",\"formautofill@mozilla.org\":\"b0aedb7f-3dfc-43ba-858a-98e80cf1cb21\",\"pictureinpicture@mozilla.org\":\"d229d5fc-a721-47b8-8c2f-77f41ab66db5\",\"screenshots@mozilla.org\":\"b1d537e4-b7d2-4aca-812f-b700e9ae25de\",\"webcompat-reporter@mozilla.org\":\"9859d673-097b-4b79-9d1d-68099fa22b86\",\"webcompat@mozilla.org\":\"fb5d02a7-c13b-4d77-811a-2a3deb94948b\",\"default-theme@mozilla.org\":\"d917bf94-43dc-4575-91c8-4cb7a59eeb87\",\"google@search.mozilla.org\":\"a8bc5028-af4f-4d18-b11c-f6a9174218c0\",\"wikipedia@search.mozilla.org\":\"9fb307e7-bf54-4d08-bc4f-30c8c42911ec\",\"yandex@search.mozilla.org\":\"a1f1f5fd-3121-4f3b-aeb0-ddf0883aab49\",\"ddg@search.mozilla.org\":\"d4208ffb-99ba-4e4d-9555-5bb8ef2f32f4\",\"priceru@search.mozilla.org\":\"d2f03367-a8f3-411f-a10f-8322b806dc89\",\"mailru@search.mozilla.org\":\"e8cac0f1-d613-4218-967a-d9b889a6a4ba\",\"ozonru@search.mozilla.org\":\"814e455d-5178-41f1-80e0-d2d7d4de9e0b\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1621699021);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx-shader-check.build-version", "20210504152106");
user_pref("gfx-shader-check.device-id", "0x1b81");
user_pref("gfx-shader-check.driver-version", "27.21.14.6140");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "88.0.1");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x1b81");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "27.21.14.6140");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("sanity-test.device-id", "0x1b81");
user_pref("sanity-test.driver-version", "27.21.14.6140");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20210504152106");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.sandbox.content.tempDirSuffix", "{270426b3-ab22-425f-a5ac-f4e046cb48ec}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{6ac1ca09-4792-48ee-bd9c-688e64d4d2ee}");
user_pref("toolkit.startup.last_success", 1621699018);
user_pref("toolkit.telemetry.cachedClientID", "de00a0e9-d0d3-4378-bd03-2e057f747716");
user_pref("toolkit.telemetry.previousBuildID", "20210504152106");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
